import { BriefcaseBusiness, CalendarDays, GraduationCap, UserRound } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { getAlumniDashboard } from "../../services/alumniPortalService";
import { getAlumniEvents } from "../../services/eventService";
import "./AlumniDashboard.css";
import "./AlumniDashboardEvents.css";

export default function AlumniDashboard() {
  const [profile, setProfile] = useState(null); const [error, setError] = useState(""); const [events, setEvents] = useState([]);
  useEffect(() => { getAlumniDashboard().then((response) => setProfile(response.data?.profile || null)).catch((requestError) => setError(requestError.response?.data?.message || "Could not load your dashboard.")); getAlumniEvents({ page: 0, size: 3 }).then((response) => setEvents(response.data?.data?.content || [])); }, []);
  const name = profile ? [profile.firstName, profile.middleName, profile.lastName].filter(Boolean).join(" ") : "Alumni"; const initial = name.charAt(0).toUpperCase();
  return <main className="alumni-main"><header className="alumni-topbar"><div><p className="alumni-eyebrow">KJCOEMR Connect — Alumni Portal</p><h1>Welcome back, {profile?.firstName || "Alumni"}.</h1><p>Your alumni identity and professional profile—always in one place.</p></div><div className="alumni-top-avatar">{initial || "A"}</div></header>{error && <p className="alumni-page-error">{error}</p>}{!profile && !error && <div className="alumni-loading-card">Loading your profile…</div>}{profile && <><section className="alumni-identity-card"><div><p>Your Alumni ID</p><strong>{profile.alumniId}</strong><span>Keep this ID for alumni-related communication.</span></div><Link to="/alumni/profile" className="alumni-edit-link">Edit profile</Link></section><section className="alumni-profile-summary"><article><GraduationCap size={21} /><span>Academic profile</span><strong>{profile.branch} · {profile.passoutYear}</strong></article><article><BriefcaseBusiness size={21} /><span>Professional profile</span><strong>{profile.jobRole}</strong><small>{profile.company}</small></article><article><UserRound size={21} /><span>Contact</span><strong>{profile.email}</strong><small>{profile.contactNumber}</small></article></section><section className="alumni-dashboard-panel alumni-events-dashboard"><div className="alumni-events-dashboard-copy"><p className="alumni-eyebrow">Upcoming events</p><h2>Events for your community</h2><p className="alumni-events-intro">Reconnect with your KJCOEMR community through upcoming gatherings.</p>{events.length ? <div className="alumni-dashboard-event-list">{events.map((event) => { const date = new Date(event.eventDateTime); return <Link className="alumni-dashboard-event" to={`/alumni/events/${event.id}`} key={event.id}><div className="alumni-dashboard-event-date"><CalendarDays size={17} /><span>{date.toLocaleDateString(undefined, { day: "numeric", month: "short" })}</span></div><div><strong>{event.title}</strong><span>{date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} · {event.venue}</span></div><b>View →</b></Link>; })}</div> : <div className="alumni-events-no-upcoming"><CalendarDays size={19} /><span>No upcoming events are available yet.</span></div>}</div><Link to="/alumni/events" className="alumni-primary-action">Explore events</Link></section></>}</main>;
}
