import { BriefcaseBusiness, CalendarDays, GraduationCap, Megaphone, UserRound } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { getAlumniDashboard } from "../../services/alumniPortalService";
import { getAlumniUpcomingEvents } from "../../services/eventService";
import { getAlumniAnnouncements } from "../../services/announcementService";
import "./AlumniDashboard.css";
import "./AlumniDashboardEvents.css";

export default function AlumniDashboard() {
  const [profile, setProfile] = useState(null); const [error, setError] = useState(""); const [events, setEvents] = useState([]); const [announcements, setAnnouncements] = useState([]);
  useEffect(() => { getAlumniDashboard().then((response) => setProfile(response.data?.profile || null)).catch((requestError) => setError(requestError.response?.data?.message || "Could not load your dashboard.")); getAlumniUpcomingEvents({ page: 0, size: 3 }).then((response) => setEvents(response.data?.data?.content || [])).catch(() => {}); getAlumniAnnouncements({ page: 0, size: 3 }).then((response) => setAnnouncements(response.data?.data?.content || [])).catch(() => {}); }, []);
  const name = profile ? [profile.firstName, profile.middleName, profile.lastName].filter(Boolean).join(" ") : "Alumni"; const initial = name.charAt(0).toUpperCase();
  return <main className="alumni-main"><header className="alumni-topbar"><div><p className="alumni-eyebrow">KJCOEMR Connect — Alumni Portal</p><h1>Welcome back, {profile?.firstName || "Alumni"}.</h1><p>Your alumni identity and professional profile—always in one place.</p></div><div className="alumni-top-avatar">{initial || "A"}</div></header>{error && <p className="alumni-page-error">{error}</p>}{!profile && !error && <div className="alumni-loading-card">Loading your profile…</div>}{profile && <><section className="alumni-identity-card"><div><p>Your Alumni ID</p><strong>{profile.alumniId}</strong><span>Keep this ID for alumni-related communication.</span></div><Link to="/alumni/profile" className="alumni-edit-link">Edit profile</Link></section><section className="alumni-profile-summary"><article><GraduationCap size={21} /><span>Academic profile</span><strong>{profile.branch} · {profile.passoutYear}</strong></article><article><BriefcaseBusiness size={21} /><span>Professional profile</span><strong>{profile.jobRole}</strong><small>{profile.company}</small></article><article><UserRound size={21} /><span>Contact</span><strong>{profile.email}</strong><small>{profile.contactNumber}</small></article></section><section className="alumni-dashboard-community-grid"><CommunityPanel eyebrow="Upcoming events" title="Events for your community" action="Explore events" to="/alumni/events" empty="No upcoming events are available yet.">{events.map((event) => { const date = new Date(event.eventDateTime); return <Link className="alumni-dashboard-event" to={`/alumni/events/${event.id}`} key={event.id}><div className="alumni-dashboard-event-date"><CalendarDays size={17} /><span>{date.toLocaleDateString(undefined, { day: "numeric", month: "short" })}</span></div><div><strong>{event.title}</strong><span>{date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} · {event.venue}</span></div><b>View →</b></Link>; })}</CommunityPanel><CommunityPanel eyebrow="Community news" title="Latest announcements" action="View all" to="/alumni/announcements" empty="No announcements are available yet.">{announcements.map((item) => <Link className="alumni-dashboard-announcement" to="/alumni/announcements" key={item.id}><div><span className={`alumni-dashboard-priority ${item.priority?.toLowerCase()}`}>{item.priority === "NORMAL" ? "UPDATE" : item.priority}</span><strong>{item.title}</strong><small>{item.message}</small></div><Megaphone size={17} /></Link>)}</CommunityPanel></section></>}</main>;
}

function CommunityPanel({ eyebrow, title, action, to, empty, children }) { return <section className="alumni-dashboard-panel alumni-community-panel"><div className="alumni-community-heading"><p className="alumni-eyebrow">{eyebrow}</p><h2>{title}</h2></div><div className="alumni-community-list">{children.length ? children : <div className="alumni-events-no-upcoming"><CalendarDays size={19} /><span>{empty}</span></div>}</div><Link to={to} className="alumni-primary-action">{action}</Link></section>; }
