package com.kjalumni.event.controller;
import com.kjalumni.auth.entity.User; import com.kjalumni.common.response.ApiResponse; import com.kjalumni.event.dto.*; import com.kjalumni.event.service.EventService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.UUID;
import org.springframework.http.*;
@RestController @RequiredArgsConstructor public class EventController { private final EventService service;
 @GetMapping("/api/public/events") public ApiResponse<Page<EventResponse>> publicEvents(@PageableDefault(size=3,sort="eventDateTime") Pageable p){return ok("Upcoming events fetched successfully.",service.publicEvents(p));}
 @PostMapping("/api/admin/events") public ApiResponse<EventResponse> create(@Valid @RequestBody EventRequest r,@AuthenticationPrincipal User u){return ok("Event created successfully.",service.create(r,u));}
 @GetMapping("/api/admin/events") public ApiResponse<Page<EventResponse>> adminEvents(@AuthenticationPrincipal User u,@PageableDefault(size=10,sort="eventDateTime") Pageable p){return ok("Events fetched successfully.",service.adminEvents(u,p));}
 @GetMapping("/api/admin/events/upcoming") public ApiResponse<Page<EventResponse>> adminUpcomingEvents(@AuthenticationPrincipal User u,@PageableDefault(size=50) Pageable p){return ok("Upcoming events fetched successfully.",service.adminUpcomingEvents(u,p));}
 @GetMapping("/api/admin/events/history") public ApiResponse<Page<EventResponse>> adminEventHistory(@AuthenticationPrincipal User u,@PageableDefault(size=50) Pageable p){return ok("Event history fetched successfully.",service.adminEventHistory(u,p));}
 @GetMapping("/api/admin/events/{id}") public ApiResponse<EventResponse> adminEvent(@PathVariable UUID id,@AuthenticationPrincipal User u){return ok("Event fetched successfully.",service.adminEvent(id,u));}
 @PutMapping("/api/admin/events/{id}") public ApiResponse<EventResponse> update(@PathVariable UUID id,@Valid @RequestBody EventRequest r,@AuthenticationPrincipal User u){return ok("Event updated successfully.",service.update(id,r,u));}
 @DeleteMapping("/api/admin/events/{id}") public ApiResponse<Void> cancel(@PathVariable UUID id,@AuthenticationPrincipal User u){service.cancel(id,u);return ok("Event deleted successfully.",null);}
 @GetMapping("/api/admin/events/{id}/attendees") public ApiResponse<Page<EventAttendeeResponse>> attendees(@PathVariable UUID id,@AuthenticationPrincipal User u,@PageableDefault(size=50,sort="createdAt") Pageable p){return ok("Event attendees fetched successfully.",service.attendees(id,u,p));}
 @PostMapping("/api/admin/events/{id}/attendees/message") public ApiResponse<Void> sendAttendeeUpdate(@PathVariable UUID id,@Valid @RequestBody EventAttendeeMessageRequest r,@AuthenticationPrincipal User u){service.sendAttendeeUpdate(id,r,u);return ok("Update is being sent to RSVP alumni.",null);}
 @GetMapping("/api/admin/events/{id}/attendees/export") public ResponseEntity<byte[]> exportAttendees(@PathVariable UUID id,@AuthenticationPrincipal User u){return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=event-attendees.csv").contentType(MediaType.parseMediaType("text/csv")).body(service.attendeeCsv(id,u));}
 @GetMapping("/api/alumni/events") public ApiResponse<Page<EventResponse>> alumniEvents(@AuthenticationPrincipal User u,@PageableDefault(size=10,sort="eventDateTime") Pageable p){return ok("Events fetched successfully.",service.alumniEvents(u,p));}
 @GetMapping("/api/alumni/events/upcoming") public ApiResponse<Page<EventResponse>> alumniUpcomingEvents(@AuthenticationPrincipal User u,@PageableDefault(size=50) Pageable p){return ok("Upcoming events fetched successfully.",service.alumniUpcomingEvents(u,p));}
 @GetMapping("/api/alumni/events/history") public ApiResponse<Page<EventResponse>> alumniEventHistory(@AuthenticationPrincipal User u,@PageableDefault(size=50) Pageable p){return ok("Event history fetched successfully.",service.alumniEventHistory(u,p));}
 @GetMapping("/api/alumni/events/{id}") public ApiResponse<EventResponse> alumniEvent(@PathVariable UUID id,@AuthenticationPrincipal User u){return ok("Event fetched successfully.",service.alumniEvent(id,u));}
 @PostMapping("/api/alumni/events/{id}/rsvp") public ApiResponse<EventResponse> rsvp(@PathVariable UUID id,@AuthenticationPrincipal User u){return ok("RSVP confirmed.",service.rsvp(id,u));}
 @DeleteMapping("/api/alumni/events/{id}/rsvp") public ApiResponse<EventResponse> withdrawRsvp(@PathVariable UUID id,@AuthenticationPrincipal User u){return ok("RSVP withdrawn.",service.withdrawRsvp(id,u));}
 private <T> ApiResponse<T> ok(String m,T d){return ApiResponse.<T>builder().success(true).message(m).data(d).build();}
}
